dspinellis/git-issue

gi.sh

The usage text for the watcher command said "tag" rather than "watcher" in the usage example.

Corrected usage text for watcher.

---

test.sh

The test led to problems with Ubuntu (tested 14.04 and 16.04) sh (dash), i.e. running `./test.sh`. Using export for the test editor configuration fixes this.

Use export for VISUAL in test to improve compatibility

---

gi.sh

The proposed "tags" command lists a count of all the unique tags currently in use across all issues. Facilitates familiarization with organization and status of a project and searching for items based on tags if you don't know all the tags. Supports discovery of possibly tag misspellings.

Added 'tags' command to list all defined tags in all issues.

---

.travis.yml
Makefile
README.md
git-issue.1
git-issue.sh
sync-docs.sh
test.sh

Make it look like git's own help:
* Remove repetitive `git issue`
* Remove repetitive colons
* Remove repetitive fullstops
* Align commands and explanations like `git help`
* Group commands logically and add headers
* Rephrase some help texts for clarity

Improve `git issue help` output

---

README.md
git-issue.1
git-issue.sh
test.sh

First and unrelated, this PR includes the following general improvements:
* Use a temp directory to preserve test artifacts after a test run (to ease debugging)
* Make the test script return 0 only when all tests are successful
* Add a test that checks whether `git issue new` fails if an empty file is given as description
Then it includes an implementation for `git issue edit`:
* The commit date/times of a new issue allocation and it's description creation are now made identical (to have an accurate edit history, based on the description file, which is created separately after the issue is opened and a SHA is assigned)
* The edit function fails when the target file is unchanged (to be able to detect an aborted edit operation)
* The edit operation is added, including doc updates and tests …

Implement git issue edit

---

gi-completion.sh

The old reglular expression for autocompleting subcommands did not fit the current help output.

fix autocompletion of subcommands

---

gi-completion.sh

autocompleting open issues should work for the ``milestone`` subcommand, too.

allow autocompletion for the milestone subcommand

---

git-issue.sh

Not sure what happened here (did the GitHub API output change?), but the test suite fails without this patch and succeeds with.

Fix importing GitHub issues' milestones

---

git-issue.sh

It is customary for /usr/local to contain software installed by the
local system administrator/owner and for that to override the same
software if provided at a system-wide level (e.g. in /usr/lib)
This address one of the issues touched on in #61 but does not fix
the key issue (IMHO) which is that `make install PREFIX=$HOME`
does not result in a working `git issue` so not marking it as fixed
in these commits.

library search: Swap precedence of /usr{/local,}/lib

---

lib/git-issue/import-export.sh

Currently
```
git issue init
git issue import gitlab {username} {reponame}
git issue export gitlab {username} {reponame}
```
outputs `Cannot find import commit.` to stderr. It should export the changes made to gitlab. 
This tiny PR fixes this bug.

Fix gitlab export error

---

lib/git-issue/import-export.sh

`git issue export gitlab {username} {reponame}` did not work as expected on Mac OSX due to the bug found in https://github.com/dspinellis/git-issue/issues/70#issuecomment-607022134
This PR fixes that.

Fix gitlab export feature due to the grep header bug

---

lib/git-issue/import-export.sh

Addresses #72 . Gitlab apparently returns "link:" in the HTTP header with a lowercase 'L', confusing the regex searching for the next page.

fix Gitlab pagination issue

---

lib/git-issue/import-export.sh

https://github.com/dspinellis/git-issue/blob/master/lib/git-issue/import-export.sh#L627 could be an empty string, which makes https://github.com/dspinellis/git-issue/blob/master/lib/git-issue/import-export.sh#L911 this call to fail (because https://github.com/dspinellis/git-issue/blob/master/lib/git-issue/import-export.sh#L90-L94 this line fails)

Fix empty endpoint bug

---

README.md
git-issue.1
sync-docs.sh

Man pages require no leading whitespace for a line to be wrapped to the one preceding it. These commits update sync-docs.sh to remove that whitespace, update the README to keep the lists working, and finally add an updated git-issue.1.

Fix whitespace in git-issue.1.

---

lib/git-issue/import-export.sh

The code before replaced the start of the link header with the literal
string "[Ll]ink". This changes it to the correct string "Link".

Fix rest_next_page_url for page 2 and up.

---

test.sh

Mainly useful when diagnosing issues with git-issue when in another git repository

allow tesh.sh to run in any directory

---

lib/git-issue/import-export.sh

Fix #84: Ensure `import` and `export` find the same issue directory.
I have added lower casing to import/export functions that parse command line arguments. I _think_ I have caught all of them. Four considerations had come to mind:
1) The `create_issue` function is used internally in a `for` loop in two other functions. So this adds redundant lower casing in these loops. This is unlikely to be a bottleneck though.
2) I did not add a test case to `test.sh`. I can have a go at it, but it will take me a bit of time to understand the test script.
3) This commit is likely to clash with #82. The pull request in there may also need to consider letter cases?
4) I decided against lower casing `$provider`. All definitions of the variable from user input are preceded by an explicit comparison to …

Lower case command arguments user and repo

---

lib/git-issue/import-export.sh

This fixes shellcheck warning about double quotes that [I was reminded of](https://github.com/dspinellis/git-issue/pull/85#issuecomment-675132851).
(I think I should not have deleted the original branch yet? If so, my bad!)

Fix shellcheck SC2086: double quote argument

---

Makefile

When git-issue is installed vi "make install" and PREFIX is overridden
from /usr/local, substitute for this in the library search path within
git-issue. Fixes #61.
This uses a GNU Makefile feature (text substitution) to avoid the path
separator '/' being interpreted as the substitution delimiter for sed.

Substitute /usr/local for PREFIX in search path

---

git-issue.sh

The README states
> * `git issue list`: List open issues (or all with `-a`).
>    An optional argument can show issues matching a tag or milestone.
My expectation in this case was that when searching for tag I would only get open issues with that tag (unless `-a` is provided). This pull request changes the working of `git issue list` to match that expectation, with the exception that when the tag that is searched for is "closed" `-a` is implied.

git issue list: only show open issues unless -a is passed

---

lib/git-issue/import-export.sh

Replace using seq with the jq range command.
Improves portability, as GNU seq is not immediately available on all target platforms.
This should fix https://github.com/dspinellis/git-issue/issues/98

Remove dependency on GNU seq

---

lib/git-issue/import-export.sh

git issue import can fetch issues from origin with no arguments
